"""Scrape source code files from git repositories.

Reads git-tracked files, applies exclusion filters (adapted from
scripts/repo_audit.py), and writes one JSONL record per file.
"""

import json
import logging
import re
import subprocess
from pathlib import Path

log = logging.getLogger(__name__)

# ── Extensions to include ────────────────────────────────────────────
CODE_EXTENSIONS = {
    ".py", ".ts", ".tsx", ".js", ".jsx",
    ".go", ".rs", ".java",
    ".sql", ".sh",
}

# ── Excluded extensions (binary, data, media, lock files) ────────────
# Adapted from scripts/repo_audit.py EXCLUDED_EXTENSIONS
EXCLUDED_EXTENSIONS = {
    # Data/serialization
    ".ipynb", ".csv", ".tsv", ".parquet", ".pkl", ".pickle",
    ".h5", ".hdf5", ".npy", ".npz", ".feather", ".arrow", ".avro", ".orc",
    ".xls", ".xlsx", ".ods", ".sqlite", ".db",
    # NLP/ML
    ".tab", ".sense", ".noun", ".verb", ".adj", ".adv", ".exc", ".rev", ".bib",
    ".bin", ".model", ".safetensors", ".joblib", ".sav",
    ".pb", ".onnx", ".pt", ".pth",
    # Media/fonts
    ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".bmp", ".webp",
    ".mp4", ".mp3", ".wav", ".ttf", ".woff", ".woff2", ".eot",
    # Compressed
    ".zip", ".tar", ".gz", ".bz2", ".tgz",
    # Documents
    ".pdf", ".doc", ".docx",
    # Certificates
    ".pem", ".crt", ".key",
    # Other noise
    ".lock", ".min.js", ".min.css", ".map", ".bat", ".dat",
}

# ── Excluded filenames ───────────────────────────────────────────────
EXCLUDED_FILENAMES = {
    # Lock files
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "uv.lock",
    "poetry.lock", "Pipfile.lock", "composer.lock", "Gemfile.lock",
    "go.sum", "cargo.lock",
    # Git/editor config
    ".gitignore", ".gitattributes", ".gitmodules",
    ".editorconfig", ".prettierrc", ".eslintrc",
    # License/changelog
    "LICENSE", "LICENSE.md", "LICENSE.txt", "NOTICE",
    "CHANGELOG.md", "CHANGES.md",
    # Python packaging metadata
    "RECORD", "WHEEL", "METADATA",
    # NLP data files (no extension)
    "tokenizer", "moves", "key2row", "vectors", "cfg",
}

# ── Excluded path patterns ───────────────────────────────────────────
EXCLUDED_PATH_PATTERNS = [
    re.compile(r"(^|/)vendor/"),
    re.compile(r"(^|/)third_party/"),
    re.compile(r"(^|/)node_modules/"),
    re.compile(r"(^|/)\.venv/"),
    re.compile(r"(^|/)venv/"),
    re.compile(r"(^|/)site-packages/"),
    re.compile(r"(^|/)openapi/"),
    re.compile(r"(^|/)openapi_client/"),
    re.compile(r"(^|/)generated/"),
    re.compile(r"_pb2\.py$"),
    re.compile(r"_pb2_grpc\.py$"),
    re.compile(r"\.pb\.go$"),
    re.compile(r"(^|/)alembic/versions/"),
    re.compile(r"(^|/)dist/"),
    re.compile(r"(^|/)build/"),
    re.compile(r"(^|/)\.next/"),
    re.compile(r"(^|/)__pycache__/"),
    re.compile(r"(^|/)\.vscode/"),
    re.compile(r"(^|/)\.idea/"),
    re.compile(r"(^|/)swagger-ui/"),
    re.compile(r"(^|/)static/swagger"),
    re.compile(r"(^|/)htmlcov/"),
    re.compile(r"(^|/)\.coverage"),
    re.compile(r"(^|/)fixtures/.*\.json$"),
    re.compile(r"(^|/)snapshots/"),
    re.compile(r"(^|/)__snapshots__/"),
    re.compile(r"(^|/)data/corpora/"),
    re.compile(r"(^|/)data/tokenizers/"),
    re.compile(r"(^|/)data/raw/"),
    re.compile(r"(^|/)output/model-"),
    re.compile(r"(^|/)load_test/"),
    re.compile(r"(^|/)stopwords/"),
]

# Auto-generated airflow DAGs
_AUTOGEN_DAG_RE = re.compile(
    r"^dags/(shopify/shopify-|hospitality/[^/]+/|ecommerce/[^/]+/|marine/[^/]+/)"
)

# Size limits
_MIN_FILE_BYTES = 100  # skip empty stubs
_MAX_FILE_BYTES = 100_000  # skip huge auto-generated files


def _run_git(repo_path: str, args: list[str]) -> str:
    """Run a git command and return stdout."""
    result = subprocess.run(
        ["git", "-C", repo_path, *args],
        capture_output=True,
        text=True,
        timeout=60,
    )
    if result.returncode != 0:
        log.warning("git command failed in %s: %s", repo_path, result.stderr.strip())
        return ""
    return result.stdout


def _should_exclude(filepath: str) -> bool:
    """Check if a file should be excluded from code scraping."""
    basename = Path(filepath).name
    ext = Path(filepath).suffix.lower()

    # Must be a code extension
    if ext not in CODE_EXTENSIONS:
        return True

    # Excluded by extension (redundant with above, but catches edge cases like .min.js)
    if ext in EXCLUDED_EXTENSIONS:
        return True

    # Excluded filenames
    if basename in EXCLUDED_FILENAMES:
        return True

    # Empty __init__.py files are noise
    if basename == "__init__.py":
        return True  # will be checked by size filter anyway

    # Path patterns
    for pat in EXCLUDED_PATH_PATTERNS:
        if pat.search(filepath):
            return True

    # Autogenerated DAGs
    if _AUTOGEN_DAG_RE.search(filepath):
        return True

    return False


def _expand_repos(patterns: list[str]) -> list[str]:
    """Expand glob patterns in repo paths, filtering to git repos only."""
    import glob
    paths: list[str] = []
    for pattern in patterns:
        expanded = str(Path(pattern).expanduser())
        matches = sorted(glob.glob(expanded))
        if not matches:
            paths.append(pattern)
            continue
        for m in matches:
            p = Path(m).resolve()
            if p.is_dir() and (p / ".git").is_dir():
                paths.append(str(p))
    # Deduplicate preserving order
    seen: set[str] = set()
    unique: list[str] = []
    for p in paths:
        resolved = str(Path(p).resolve())
        if resolved not in seen:
            seen.add(resolved)
            unique.append(resolved)
    return unique


def scrape_repo(repo_path: str) -> list[dict]:
    """Read all code files from a single repo. Returns flat records."""
    remote = _run_git(repo_path, ["remote", "get-url", "origin"]).strip()
    repo_name = remote.split("/")[-1].replace(".git", "") if remote else Path(repo_path).name

    # Get all tracked files
    ls_output = _run_git(repo_path, ["ls-files"])
    if not ls_output:
        return []

    all_files = [f for f in ls_output.strip().split("\n") if f]

    records: list[dict] = []
    skipped = 0

    for filepath in all_files:
        if _should_exclude(filepath):
            skipped += 1
            continue

        full_path = Path(repo_path) / filepath
        try:
            size = full_path.stat().st_size
        except OSError:
            continue

        if size < _MIN_FILE_BYTES or size > _MAX_FILE_BYTES:
            skipped += 1
            continue

        try:
            content = full_path.read_text(errors="replace")
        except (OSError, UnicodeDecodeError):
            skipped += 1
            continue

        # Extra sanity: skip files that are mostly non-text (binary snuck through)
        if _is_likely_binary(content):
            skipped += 1
            continue

        ext = Path(filepath).suffix.lower()
        language = _ext_to_language(ext)

        records.append({
            "repo": repo_name,
            "path": filepath,
            "language": language,
            "size_bytes": size,
            "content": content,
        })

    log.info("Scraped %d code files from %s (skipped %d)", len(records), repo_name, skipped)
    return records


def _is_likely_binary(content: str, sample_size: int = 1024) -> bool:
    """Heuristic: if >10% of first 1K chars are control characters, it's binary."""
    sample = content[:sample_size]
    if not sample:
        return True
    control = sum(1 for c in sample if ord(c) < 32 and c not in "\n\r\t")
    return control / len(sample) > 0.1


def _ext_to_language(ext: str) -> str:
    """Map file extension to language name."""
    return {
        ".py": "python",
        ".ts": "typescript",
        ".tsx": "typescript",
        ".js": "javascript",
        ".jsx": "javascript",
        ".go": "go",
        ".rs": "rust",
        ".java": "java",
        ".sql": "sql",
        ".sh": "shell",
    }.get(ext, "unknown")


def scrape(raw_dir: Path, config: dict) -> None:
    """Scrape all configured repos, write to raw/code.jsonl."""
    repos = config.get("repos", [])
    if not repos:
        log.info("No code repos configured, skipping")
        return

    expanded_repos = _expand_repos(repos)
    skip_repos = set(config.get("skip_repos", []))
    log.info("Resolved %d git repos from %d patterns (skipping %s)", len(expanded_repos), len(repos), skip_repos or "none")

    raw_dir.mkdir(parents=True, exist_ok=True)
    output_path = raw_dir / "code.jsonl"

    records: list[dict] = []
    for repo_path in expanded_repos:
        if not Path(repo_path).is_dir():
            log.warning("Repo not found: %s", repo_path)
            continue
        repo_name = Path(repo_path).name
        if repo_name in skip_repos:
            log.info("Skipping %s (in skip_repos)", repo_name)
            continue
        records.extend(scrape_repo(repo_path))

    with open(output_path, "w") as f:
        for rec in records:
            f.write(json.dumps(rec) + "\n")

    log.info("Code scrape complete: %d files written to %s", len(records), output_path)
